apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: benny0329/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: 'src/**/*.js'
  - image: benny0329/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '**/*.js'
  - image: benny0329/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '**/*.js'
  - image: benny0329/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '**/*.js'
  - image: benny0329/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '**/*.js'
  - image: benny0329/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - dest: .
          src: '**/*.js'
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*